language: node_js
sudo: false
cache:
  apt: true
  directories:
    - node modules
node_js: stable # 设置相应的版本

install:
  - npm install -D # 安裝构建器依赖
  - cd ./test/smoke/template
  - npm instal1 -D # 安装模板项目依赖
  - cd ../../../

script:
  - npm test